server:
  port: 8085

spring:
  datasource:
    username: sergey
    password: cthsq30896
    url: jdbc:mysql://localhost:3306/books_shop
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false

  messages:
    basename: lang.messages
  web:
    resources: static-locations=classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  sql:
    init:
    data-locations: classpath:data.sql,classpath:authors.sql
    schema-locations: classpath:schema.sql
    mode: always