spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/calories_tracking_service
    url: jdbc:postgresql://localhost:5433/calories_tracking_service
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: debug